/:
  controller: Main
  action: default

/404:
  controller: Main
  action: page404

/utilisateur:
  controller: User
  action: default

/ajout-d-un-utilisateur:
  controller: User
  action: add

/afficher-un-utilisateur:
  controller: User
  action: show

/afficher-les-utilisateurs:
  controller: User
  action: showAll


/register:
  controller: Security
  action: register

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/admin:
  controller: Admin/Admin
  action: index
  name: app_admin

/admin/menus:
  controller: Admin
  action: menus
  name: app_admin_menus

#-- -- USERS ADMIN -- -- #
/admin/member:
  controller: Admin/AdminUser
  action: member
  name: app_admin_member

/admin/member/delete:
  controller: Admin/AdminUser
  action: memberDelete
  name: app_admin_member_delete

/admin/member/edit:
  controller: Admin/AdminUser
  action: memberEdit
  name: app_admin_member_edit

/admin/member/add:
  controller: Admin/AdminUser
  action: memberAdd
  name: app_admin_member_add
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #

/admin/dishes:
  controller: Dishes
  action: dishes

/admin/dishes/add:
  controller: Dishes
  action: dishesAdd

#-- -- INGREDIENTS -- --#
/admin/ingredients:
  controller: Admin/Ingredients
  action: ingredients
  name: app_admin_ingredients

/admin/ingredients/add:
  controller: Admin/Ingredients
  action: ingredientsAdd
  name: app_admin_ingredients_add

/admin/ingredients/edit:
  controller: Admin/Ingredients
  action: ingredientsEdit
  name: app_admin_ingredients_edit

/admin/ingredients/delete:
  controller: Admin/Ingredients
  action: ingredientsDelete
  name: app_admin_ingredients_delete
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #
