
#-- -- MAIN -- -- #
/:
  controller: Main
  action: default
  name: app_home

/404:
  controller: Main
  action: page404
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #

#-- -- SECURITY -- -- #
/register:
  controller: Users/Security
  action: register
  name: app_register

/login:
  controller: Users/Security
  action: login
  name: app_login

/login/oauth:
  controller: Users/Security
  action: loginOAuth
  name: app_login_oauth

/logout:
  controller: Users/Security
  action: logout
  name: app_logout
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #

/admin:
  controller: Admin/Admin
  action: index
  name: app_admin

/admin/group:
  controller: Admin/Admin
  action: group
  name: app_admin_group

/admin/menus:
  controller: Admin
  action: menus
  name: app_admin_menus

#-- -- USERS ADMIN -- -- #
/admin/member:
  controller: Admin/AdminUser
  action: member
  name: app_admin_member

/admin/member/delete:
  controller: Admin/AdminUser
  action: memberDelete
  name: app_admin_member_delete

/admin/member/edit:
  controller: Admin/AdminUser
  action: memberEdit
  name: app_admin_member_edit

/admin/member/add:
  controller: Admin/AdminUser
  action: memberAdd
  name: app_admin_member_add
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #
#-- -- DISHES -- --#
/admin/dishes:
  controller: Admin/AdminDishes
  action: dishes
  name: app_admin_dishes

/admin/dishes/add:
  controller: Admin/AdminDishes
  action: dishesAdd
  name: app_admin_dishes_add

/admin/dishes/delete:
  controller: Admin/AdminDishes
  action: dishesDelete
  name: app_admin_dishes_delete

/admin/dishes/edit:
  controller: Admin/AdminDishes
  action: dishesEdit
  name: app_admin_dishes_edit

/admin/dishes/edit-ingredient:
  controller: Admin/AdminDishes
  action: dishesIngredientEdit
  name: app_admin_dishes_ingredient_edit

/admin/dishes/delete-ingredient:
  controller: Admin/AdminDishes
  action: dishesIngredientDelete
  name: app_admin_dishes_ingredient_delete

/admin/dishes/add-ingredient:
  controller: Admin/AdminDishes
  action: dishesIngredientAdd
  name: app_admin_dishes_ingredient_add


#-- -- INGREDIENTS -- --#
/admin/ingredients:
  controller: Admin/AdminIngredients
  action: ingredients
  name: app_admin_ingredients

/admin/ingredients/add:
  controller: Admin/AdminIngredients
  action: ingredientsAdd
  name: app_admin_ingredients_add

/admin/ingredients/edit:
  controller: Admin/AdminIngredients
  action: ingredientsEdit
  name: app_admin_ingredients_edit

/admin/ingredients/delete:
  controller: Admin/AdminIngredients
  action: ingredientsDelete
  name: app_admin_ingredients_delete
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #


#-- -- Appearance -- --#

/admin/appearance:
  controller: Admin/AdminAppearance
  action: appearance
  name: app_admin_appearance

#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #