
#-- -- MAIN -- -- #
/:
  controller: Main
  action: default
  name: app_home

/404:
  controller: Main
  action: page404
  name: app_404

/sitemap.xml:
  controller: Main
  action: sitemap
  name: app_sitemap

/install:
  controller: Install
  action: install
  name: app_install
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #

#-- -- SECURITY -- -- #
/register:
  controller: Users/Security
  action: register
  name: app_register

/login:
  controller: Users/Security
  action: login
  name: app_login

/reset_password:
  controller: Users/Security
  action: reset
  name: app_reset_password

/login/oauth:
  controller: Users/Security
  action: loginOAuth
  name: app_login_oauth

/logout:
  controller: Users/Security
  action: logout
  name: app_logout
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #
/admin:
  controller: Admin/Admin
  action: index
  name: app_admin

/admin/configuration:
  controller: Admin/Admin
  action: config
  name: app_admin_config
#-- -- USERS ADMIN -- -- #
/admin/user:
  controller: Admin/User/AdminUser
  action: index
  name: app_admin_user

/admin/user/delete:
  controller: Admin/User/AdminUser
  action: delete
  name: app_admin_user_delete

/admin/user/edit:
  controller: Admin/User/AdminUser
  action: edit
  name: app_admin_user_edit

/admin/user/add:
  controller: Admin/User/AdminUser
  action: add
  name: app_admin_user_add
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #
#-- -- GROUP ADMIN -- -- #
/admin/group:
  controller: Admin/User/AdminGroup
  action: index
  name: app_admin_group

/admin/group/delete:
  controller: Admin/User/AdminGroup
  action: delete
  name: app_admin_group_delete

/admin/group/edit:
  controller: Admin/User/AdminGroup
  action: edit
  name: app_admin_group_edit

/admin/group/add:
  controller: Admin/User/AdminGroup
  action: add
  name: app_admin_group_add
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #
#-- -- MENU -- --#
/admin/menu:
  controller: Admin/Restaurant/AdminMenu
  action: index
  name: app_admin_menu

/admin/menu/add:
  controller: Admin/Restaurant/AdminMenu
  action: add
  name: app_admin_menu_add

/admin/menu/delete:
  controller: Admin/Restaurant/AdminMenu
  action: delete
  name: app_admin_menu_delete

/admin/menu/edit:
  controller: Admin/Restaurant/AdminMenu
  action: edit
  name: app_admin_menu_edit

#---

/admin/menu/edit-meal:
  controller: Admin/Restaurant/AdminMenu
  action: mealEdit
  name: app_admin_menu_meal_edit

/admin/menu/delete-meal:
  controller: Admin/Restaurant/AdminMenu
  action: mealDelete
  name: app_admin_menu_meal_delete

/admin/menu/add-meal:
  controller: Admin/Restaurant/AdminMenu
  action: mealAdd
  name: app_admin_menu_meal_add




#-- -- MEAL -- --#
/admin/meal:
  controller: Admin/Restaurant/AdminMeal
  action: index
  name: app_admin_meal

/admin/meal/add:
  controller: Admin/Restaurant/AdminMeal
  action: add
  name: app_admin_meal_add

/admin/meal/delete:
  controller: Admin/Restaurant/AdminMeal
  action: delete
  name: app_admin_meal_delete

/admin/meal/edit:
  controller: Admin/Restaurant/AdminMeal
  action: edit
  name: app_admin_meal_edit

#---

/admin/meal/edit-foodstuff:
  controller: Admin/Restaurant/AdminMeal
  action: foodstuffEdit
  name: app_admin_meal_foodstuff_edit

/admin/meal/delete-foodstuff:
  controller: Admin/Restaurant/AdminMeal
  action: foodstuffDelete
  name: app_admin_meal_foodstuff_delete

/admin/meal/add-foodstuff:
  controller: Admin/Restaurant/AdminMeal
  action: foodstuffAdd
  name: app_admin_meal_foodstuff_add

#-- -- FOODSTUFF -- --#
/admin/foodstuff:
  controller: Admin/Restaurant/AdminFoodstuff
  action: index
  name: app_admin_foodstuff

/admin/foodstuff/add:
  controller: Admin/Restaurant/AdminFoodstuff
  action: add
  name: app_admin_foodstuff_add

/admin/foodstuff/edit:
  controller: Admin/Restaurant/AdminFoodstuff
  action: edit
  name: app_admin_foodstuff_edit

/admin/foodstuff/delete:
  controller: Admin/Restaurant/AdminFoodstuff
  action: delete
  name: app_admin_foodstuff_delete
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #

#-- -- appearance -- --#
/admin/appearance:
  controller: Admin/Appearance/Appearance
  action: index
  name: app_admin_appearance

#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #


#-- -- PAGE -- --#
/admin/page:
  controller: Admin/Page/Page
  action: index
  name: app_admin_page

/admin/page/add:
  controller: Admin/Page/Page
  action: add
  name: app_admin_page_add

/admin/page/edit:
  controller: Admin/Page/Page
  action: edit
  name: app_admin_page_edit

/admin/page/delete:
  controller: Admin/Page/Page
  action: delete
  name: app_admin_page_delete
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #

#-- -- RESERVATION -- --#
/admin/reservation:
  controller: Admin/Reservation/Reservation
  action: index
  name: app_admin_reservation

/admin/reservation/delete:
  controller: Admin/Reservation/Reservation
  action: delete
  name: app_admin_reservation_delete

/admin/reservation/validate:
  controller: Admin/Reservation/Reservation
  action: validate
  name: app_admin_reservation_validate

/admin/reservation/add:
  controller: Admin/Reservation/Reservation
  action: add
  name: app_admin_reservation_add

/admin/reservation/edit:
  controller: Admin/Reservation/Reservation
  action: edit
  name: app_admin_reservation_edit
#-- -- REVIEW -- --#
/admin/review:
  controller: Admin/Review/Review
  action: index
  name: app_admin_review

/admin/review/show:
  controller: Admin/Review/Review
  action: show
  name: app_admin_review_show

/admin/review/delete:
  controller: Admin/Review/Review
  action: delete
  name: app_admin_review_delete
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #

#-- -- REPORT -- --#
/admin/report:
  controller: Admin/Review/Report
  action: index
  name: app_admin_report

/admin/report/show:
  controller: Admin/Review/Report
  action: show
  name: app_admin_report_show

/admin/report/delete:
  controller: Admin/Review/Report
  action: delete
  name: app_admin_report_delete
#-- -- -- -- -- -- -- -- -- -- -- -- -- -- #