/:
  controller: Main
  action: default

/404:
  controller: Main
  action: page404

/utilisateur:
  controller: User
  action: default

/ajout-d-un-utilisateur:
  controller: User
  action: add

/afficher-un-utilisateur:
  controller: User
  action: show

/afficher-les-utilisateurs:
  controller: User
  action: showAll


/register:
  controller: Security
  action: register

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/admin:
  controller: Admin
  action: index

/admin/menus:
  controller: Admin
  action: menus

/admin/member:
  controller: Admin
  action: member

/admin/member/delete:
  controller: Admin
  action: memberDelete

/admin/member/edit:
  controller: Admin
  action: memberEdit

/admin/member/add:
  controller: Admin
  action: memberAdd

/admin/dishes:
  controller: Admin
  action: dishes

/admin/ingredients:
  controller: Admin
  action: ingredients